import { Request, Response } from 'express'
import Project from '../models/Project'
import Task from '../models/Task'
import User from '../models/User'
import mongoose from 'mongoose'

// Helper to simulate elegant, context-aware AI text generation
const generateMockAISummary = (projectName: string, stats: any, bottlenecks: string[], recommendations: string[]) => {
  return `### 🤖 TaskNest AI Project Advisory Report

**Project Analysis: "${projectName}"**

Based on our real-time workspace scan, here is a professional diagnostic of your project health:

#### 📊 Performance Analytics
* **Completion Rate:** ${stats.completionRate}%
* **Active Workflow Load:** **${stats.activeTasks}** task(s) in active development (In Progress / Review)
* **Backlog Velocity:** **${stats.todoTasks}** pending items in To Do
* **Closed Velocity:** **${stats.doneTasks}** completed items in Done

#### 🚨 Risk Assessment & Bottlenecks
${bottlenecks.length > 0 
  ? bottlenecks.map(b => `* ⚠️ **Bottleneck identified:** ${b}`).join('\n')
  : `* ✅ **Excellent Work!** No critical bottlenecks, high-priority blocks, or immediate high-risk delays are currently detected.`
}

#### 🎯 Strategic Recommendations
${recommendations.map((r, i) => `${i + 1}. **${r}**`).join('\n')}

---
*Generated by **TaskNest Gemini Pro Copilot** • Context-aware workspace intelligence*`
}

export const summarizeProject = async (req: any, res: Response) => {
  try {
    const { projectId } = req.params

    if (!mongoose.Types.ObjectId.isValid(projectId)) {
      return res.status(400).json({ success: false, message: 'Invalid Project ID' })
    }

    const project = await Project.findById(projectId)
    if (!project) {
      return res.status(404).json({ success: false, message: 'Project not found' })
    }

    const tasks = await Task.find({ project: projectId })

    const total = tasks.length
    const todoTasks = tasks.filter(t => t.status === 'todo').length
    const inProgressTasks = tasks.filter(t => t.status === 'in-progress').length
    const reviewTasks = tasks.filter(t => t.status === 'review').length
    const doneTasks = tasks.filter(t => t.status === 'done').length

    const activeTasks = inProgressTasks + reviewTasks
    const completionRate = total > 0 ? Math.round((doneTasks / total) * 100) : 0

    // Detect bottlenecks
    const bottlenecks: string[] = []
    const criticalTasks = tasks.filter(t => t.priority === 'critical' && t.status !== 'done')
    const highTasks = tasks.filter(t => t.priority === 'high' && t.status !== 'done')

    if (criticalTasks.length > 0) {
      bottlenecks.push(`There are **${criticalTasks.length} critical priority tasks** still active. Specifically, "${criticalTasks[0].title}" requires immediate attention.`)
    }
    if (highTasks.length > 1) {
      bottlenecks.push(`Workload skew: **${highTasks.length} high priority tasks** are competing for developer focus in active columns.`)
    }
    if (inProgressTasks > 4) {
      bottlenecks.push(`High multi-tasking index: **${inProgressTasks} tasks are In Progress concurrently**. This may lead to context switching delays.`)
    }

    // Formulate recommendations
    const recommendations: string[] = []
    if (todoTasks > doneTasks && doneTasks === 0) {
      recommendations.push('Initiate high-impact setup tasks to kick off the planning phase.')
    }
    if (criticalTasks.length > 0) {
      recommendations.push('Reassign active resources to close out critical blockers first.')
    }
    if (reviewTasks > 2) {
      recommendations.push('Prioritize pull request review and client sign-off on outstanding review tasks.')
    }
    if (completionRate < 50 && project.dueDate && new Date(project.dueDate) < new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)) {
      recommendations.push('Warning: Due date is approaching. Consider extending sprint capacity or slimming scope.')
    }
    if (recommendations.length === 0) {
      recommendations.push('Maintain current velocity. Project is pacing on schedule.')
      recommendations.push('Establish automated CI/CD and deployment targets to expedite future task releases.')
    }

    const aiAdvisoryMarkdown = generateMockAISummary(
      project.name, 
      { completionRate, activeTasks, todoTasks, doneTasks },
      bottlenecks,
      recommendations
    )

    res.json({
      success: true,
      data: {
        projectId,
        projectName: project.name,
        completionRate,
        totalTasks: total,
        summary: aiAdvisoryMarkdown
      }
    })
  } catch (error: any) {
    console.error('AI Summary Error:', error)
    res.status(500).json({ success: false, message: error.message || 'AI generation failed' })
  }
}

export const generateTasks = async (req: any, res: Response) => {
  try {
    const { prompt, projectId } = req.body

    if (!prompt) {
      return res.status(400).json({ success: false, message: 'AI prompt is required' })
    }

    // Formulate customized AI suggestions depending on keywords in the prompt
    let suggestedTasks: any[] = []
    const normalizedPrompt = prompt.toLowerCase()

    if (normalizedPrompt.includes('auth') || normalizedPrompt.includes('login') || normalizedPrompt.includes('security')) {
      suggestedTasks = [
        {
          title: 'Design JWT & Refresh Token Auth Architecture',
          description: 'Define secure HTTP-only cookie parameters, JWT expiration windows (15m), and redis-based token revocation tables.',
          priority: 'critical',
          status: 'todo',
          estimatedHours: 4,
          tags: ['backend', 'security']
        },
        {
          title: 'Implement Multi-Factor Authentication (2FA) OTP Setup',
          description: 'Configure Speakeasy client secret generation, secure user storage, and custom QR code enrollment UI for profile settings.',
          priority: 'high',
          status: 'todo',
          estimatedHours: 6,
          tags: ['security', 'frontend']
        },
        {
          title: 'Integrate Google & GitHub OAuth2 Login Routes',
          description: 'Establish passport strategies on the backend and wire up OAuth callback listeners inside the react-router controller.',
          priority: 'medium',
          status: 'todo',
          estimatedHours: 5,
          tags: ['oauth', 'integration']
        },
        {
          title: 'Add Helmet.js and CORS HTTP Security Headers',
          description: 'Configure helmet to protect against XSS, clickjacking, and mime-sniffing, and restrict origins inside the express router configuration.',
          priority: 'low',
          status: 'todo',
          estimatedHours: 2,
          tags: ['backend', 'security']
        }
      ]
    } else if (normalizedPrompt.includes('database') || normalizedPrompt.includes('mongodb') || normalizedPrompt.includes('schema')) {
      suggestedTasks = [
        {
          title: 'Create MongoDB Relational Schemas & Indexes',
          description: 'Establish mongoose models for Workspace, Project, Task, and User. Set compound database indexes on (project, status).',
          priority: 'high',
          status: 'todo',
          estimatedHours: 4,
          tags: ['database', 'schema']
        },
        {
          title: 'Configure Mongoose Query Pagination Middleware',
          description: 'Implement a reusable schema plugin to support limit, cursor pagination, and populate arguments dynamically.',
          priority: 'medium',
          status: 'todo',
          estimatedHours: 3,
          tags: ['backend', 'database']
        },
        {
          title: 'Draft Seed Data & Database Initialization Script',
          description: 'Write seed.ts containing realistic workspaces, teams, tasks, and mock messages. Wire to npm run seed in package.json.',
          priority: 'low',
          status: 'todo',
          estimatedHours: 3,
          tags: ['database', 'dev-ops']
        }
      ]
    } else if (normalizedPrompt.includes('ui') || normalizedPrompt.includes('theme') || normalizedPrompt.includes('design') || normalizedPrompt.includes('tailwind')) {
      suggestedTasks = [
        {
          title: 'Refactor Tailwind Theme Configuration & Color System',
          description: 'Implement dark/light HSL CSS custom tokens in index.css and wire extending values for primary, secondary, and accent colors.',
          priority: 'high',
          status: 'todo',
          estimatedHours: 4,
          tags: ['design-system', 'tailwind']
        },
        {
          title: 'Build Premium Glassmorphic Layout Components',
          description: 'Create reusable card components leveraging backdrop-blur, subtle gradients, and custom box shadows.',
          priority: 'medium',
          status: 'todo',
          estimatedHours: 5,
          tags: ['frontend', 'ui-ux']
        },
        {
          title: 'Add Smooth Page Transition Animations',
          description: 'Integrate Framer Motion presence wrappers in main App routes to allow sleek, professional slide and fade transitions.',
          priority: 'low',
          status: 'todo',
          estimatedHours: 3,
          tags: ['animations', 'frontend']
        }
      ]
    } else {
      // General fallbacks based on user inputs
      const capitalizedTopic = prompt.charAt(0).toUpperCase() + prompt.slice(1)
      suggestedTasks = [
        {
          title: `Research & Architecture Plan: ${capitalizedTopic}`,
          description: `Map out high-level technical requirements, select libraries, and establish milestones for the "${prompt}" subsystem.`,
          priority: 'high',
          status: 'todo',
          estimatedHours: 3,
          tags: ['planning']
        },
        {
          title: `Build Core API Endpoints for ${capitalizedTopic}`,
          description: `Implement Express controllers, validation schemas (Zod/Joi), and test route endpoints for CRUD actions related to "${prompt}".`,
          priority: 'high',
          status: 'todo',
          estimatedHours: 6,
          tags: ['backend', 'api']
        },
        {
          title: `Create Responsive User Interface for ${capitalizedTopic}`,
          description: `Code beautiful UI components, connect state manager (Zustand/Redux), and handle loading, empty, and error feedback states.`,
          priority: 'medium',
          status: 'todo',
          estimatedHours: 6,
          tags: ['frontend', 'ui']
        },
        {
          title: `Write Integration Tests & Documentation for ${capitalizedTopic}`,
          description: `Establish unit/integration testing suites (Jest/Supertest) and document endpoint specs inside FEATURES.md.`,
          priority: 'low',
          status: 'todo',
          estimatedHours: 4,
          tags: ['testing', 'docs']
        }
      ]
    }

    res.json({
      success: true,
      data: {
        prompt,
        projectId,
        tasks: suggestedTasks
      }
    })
  } catch (error: any) {
    console.error('AI Task Generator Error:', error)
    res.status(500).json({ success: false, message: error.message || 'AI generation failed' })
  }
}

export const chatCopilot = async (req: any, res: Response) => {
  try {
    const { message, chatHistory } = req.body

    if (!message) {
      return res.status(400).json({ success: false, message: 'Message is required' })
    }

    const normalizedMsg = message.toLowerCase()
    let aiResponse = ''

    // Gather live workspace facts to make the AI reply incredibly accurate and realistic
    const projectCount = await Project.countDocuments()
    const taskCount = await Task.countDocuments()
    const userCount = await User.countDocuments()
    const criticalTasks = await Task.find({ priority: 'critical', status: { $ne: 'done' } })
    const activeProjects = await Project.find({ status: 'in-progress' }).limit(3)

    if (normalizedMsg.includes('hello') || normalizedMsg.includes('hi ') || normalizedMsg.includes('hey')) {
      aiResponse = `Hello ${req.user.name}! I am your **TaskNest Gemini Copilot**. 🚀\n\nCurrently, I am tracking **${projectCount} active projects** and **${taskCount} tasks** across **${userCount} team members**.\n\nHow can I assist you today? You can ask me to:\n1. **Summarize a project's current health**\n2. **Draft task checklists** for new sprints\n3. **Identify workspace bottlenecks**`
    } else if (normalizedMsg.includes('status') || normalizedMsg.includes('how many') || normalizedMsg.includes('stats') || normalizedMsg.includes('overview')) {
      aiResponse = `Here is your global MERN workspace overview:\n\n* 📁 **Total Projects:** ${projectCount}\n* 🎯 **Total Tasks:** ${taskCount}\n* 👥 **Active Members:** ${userCount}\n* 🚨 **Critical Blockers:** ${criticalTasks.length} active critical task(s)\n\nWe have active work flowing smoothly across **${activeProjects.length} active development channels**: ${activeProjects.map(p => `*${p.name}*`).join(', ')}.`
    } else if (normalizedMsg.includes('bottleneck') || normalizedMsg.includes('block') || normalizedMsg.includes('delay') || normalizedMsg.includes('critical')) {
      if (criticalTasks.length > 0) {
        aiResponse = `🚨 **Workspace Bottleneck Alert!**\n\nI have identified **${criticalTasks.length} active blocker(s)** that require developer review:\n\n${criticalTasks.map((t, i) => `${i + 1}. **${t.title}** (Priority: \`CRITICAL\`) - Status: \`${t.status.toUpperCase()}\``).join('\n')}\n\nI suggest reassigning team members to address these items today to keep the sprint timeline secure.`
      } else {
        aiResponse = `✅ **Workspace health is green!**\n\nI scanned the active task queues and found **0 active critical blockers**. Everything is pacing correctly. Nice job managing your pipeline!`
      }
    } else if (normalizedMsg.includes('help') || normalizedMsg.includes('what can you do')) {
      aiResponse = `I am your advanced **AI Workspace Copilot** integrated directly into the TaskNest core database. Here is what I can do for you:\n\n* **\`Analyze Project Health\`** — Scan active tasks, detect context switching bottlenecks, and recommend adjustments.\n* **\`Smart Task Blueprinting\`** — Generate technical checklists for databases, frontend, or APIs instantly.\n* **\`Team Metrics Scan\`** — Provide summaries of workflow progress, counts, and blockers.\n\nType any message like "Give me a status update" or "Check critical blockers" to begin!`
    } else {
      aiResponse = `That is an interesting question regarding *"${message}"*.\n\nAs your **TaskNest AI Assistant**, I recommend setting up a dedicated sprint to explore this further. I can write a detailed technical task outline for you if you tell me: *"Generate tasks for [your topic]"*.\n\nLet me know how you'd like to proceed!`
    }

    res.json({
      success: true,
      data: {
        reply: aiResponse
      }
    })
  } catch (error: any) {
    console.error('AI Chat Error:', error)
    res.status(500).json({ success: false, message: error.message || 'AI chat failed' })
  }
}
